### ISSUE TITLE
Failed to bypass anti-dev tools with Lbrewolf

### ISSUE THREAD

**Issue by Zai-Kun** [Blatzar/scraping-tutorial#14]
As you mentioned in the blog post, I've installed Librewolf 131.0.3-1 and edited the config (about:config), but I still can't bypass it. Also, I have an unpatched version of Firefox on my computer; could it be interfering? 
![image](https://github.com/user-attachments/assets/69c28c1b-67eb-4946-b98b-61ef7e783dad)
![image](https://github.com/user-attachments/assets/42c678f4-0117-4a16-8d41-a1e88e4c0753)

The website i used to test dev tools detection: https://blog.aepkill.com/demos/devtools-detector

**Comment by Blatzar** [comment]
I am not sure about the case sensitivity in about:config, but I am still able to replicate the issue!

Neither patch seems to be activated in the latest Librewolf version, but I cannot find any changes in the Firefox source code nor any explicit deactivation in the Librewolf source code. Something is broken and I don't know from where. I will try to compile Firefox tomorrow with the custom patches to see if the issue lies with Librewolf or Firefox and make an appropriate issue. Thank you for pointing out the issue!

**Comment by Zai-Kun** [comment]
> I am not sure about the case sensitivity in about:config, but I am still able to replicate the issue!
> 
> Neither patch seems to be activated in the latest Librewolf version, but I cannot find any changes in the Firefox source code nor any explicit deactivation in the Librewolf source code. Something is broken and I don't know from where. I will try to compile Firefox tomorrow with the custom patches to see if the issue lies with Librewolf or Firefox and make an appropriate issue. Thank you for pointing out the issue!

Great! Thank you so much, and good luck!

**Comment by Zai-Kun** [comment]
It seems like the issue was with the case sensitivity in about:config for me. Lowercasing "LibreWolf" fixed the issue for me; now websites can't detect if I have dev tools open or not.

**Comment by Blatzar** [comment]
Ugh, looks like a nixos-specific issue then, the patches work on windows too :melting_face:

**Comment by Zai-Kun** [comment]
So, unfortunately, they removed your patch:
https://codeberg.org/librewolf/source/commit/1db9c69479cbf106d7ee7f66b52c83d45f20efc0

what do we do now? I really loved this patch. Do i have to apply the patch manually and compile libre wolf myself?

**Comment by Blatzar** [comment]
Sadly I do not have time to create a new patch. You will need to compile firefox or librewolf yourself.

**Comment by Zai-Kun** [comment]
> Sadly I do not have time to create a new patch. You will need to compile firefox or librewolf yourself.

https://codeberg.org/librewolf/source/pulls/61#issuecomment-11980809

Well i hope this patch works
